
from collections import namedtuple
from ..settings import settings

MFP_POT = namedtuple("MFP_POT",
                 ["title","annual_series",
                  "title1", "title2",
                  "start_yr",
                  "yaxis_title1","yaxis_format1",
                  "yaxis_title2","yaxis_format2"])

mfp_pot = [
    # kind 1: alles mit Level und Change
    MFP_POT(
        title="Bruttoinlandsprodukt",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_BIP_V_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Produktionspotenzial (EU)",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_YPOTEU_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. EUR",
        yaxis_format1=",.0f",
        yaxis_title2="in % zum Vorjahr",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Produktionslücke (EU)",
        title1="",
        title2="",
        annual_series="AGE_YGAPEU",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in % des Potenzials",
        yaxis_format1=",.1f",
        yaxis_title2="",
        yaxis_format2="",
    ),
        MFP_POT(
        title="Produktionspotenzial (MODEM)",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_YPOT_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. EUR",
        yaxis_format1=",.0f",
        yaxis_title2="in % zum Vorjahr",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Produktionslücke (MODEM)",
        title1="",
        title2="",
        annual_series="AGE_YGAP",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in % des Potenzials",
        yaxis_format1=",.1f",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="BIP Deflator",
        title1="Veränderung zum Vorjahr",
        title2="",
        annual_series="AGE_PBIP",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Privater Konsum",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_CP_V_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Staatskonsum",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_CST_V_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Ausrüstungsinvestitionen",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_IAU_V_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Bauinvestitionen",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_IB_V_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Exporte",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_EX_V_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Importe",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_IM_V_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Bruttoinlandsprodukt (nominal)",
        title1="Aktuelle Preise",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_BIP_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Privater Konsum (nominal)",
        title1="Aktuelle Preise",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_CP_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Staatskonsum (nominal)",
        title1="Aktuelle Preise",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_CST_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Ausrüstungsinvestitionen (nominal)",
        title1="Aktuelle Preise",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_IAU_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Bauinvestitionen (nominal)",
        title1="Aktuelle Preise",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_IB_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Exporte (nominal)",
        title1="Aktuelle Preise",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_EX_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Importe (nominal)",
        title1="Aktuelle Preise",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_IM_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Deflator Private Haushalte",
        title1="Veränderung zum Vorjahr",
        title2="",
        annual_series="AGE_PCP",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Deflator Staatskonsum",
        title1="Veränderung zum Vorjahr",
        title2="",
        annual_series="AGE_PCST",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Deflator Ausrüstungsinvestitionen",
        title1="Veränderung zum Vorjahr",
        title2="",
        annual_series="AGE_PIAU",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Deflator Bauinvestitionen",
        title1="Veränderung zum Vorjahr",
        title2="",
        annual_series="AGE_PIB",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Deflator Exporte",
        title1="Veränderung zum Vorjahr",
        title2="",
        annual_series="AGE_PEX",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Deflator Importe",
        title1="Veränderung zum Vorjahr",
        title2="",
        annual_series="AGE_PIM",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Terms of Trade",
        title1="Niveau",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_TERMTRADE",
        start_yr=settings["window_mf"].start,
        yaxis_title1="Index",
        yaxis_format1=",.3f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Konsumquote - Private Haushalte",
        title1="",
        title2="",
        annual_series="AGE_QCP",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Konsumquote - Staat",
        title1="",
        title2="",
        annual_series="AGE_QCST",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Investitionsquote - Ausrüstungen und Sonstige Investitionen",
        title1="",
        title2="",
        annual_series="AGE_QIAU",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Investitionsquote - Bauinvestitionen",
        title1="",
        title2="",
        annual_series="AGE_QIB",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Anteile am BIP - Inländische Verwendung",
        title1="",
        title2="",
        annual_series="AGE_QNI",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Anteile am BIP - Außenbeitrag",
        title1="",
        title2="",
        annual_series="AGE_QAB",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Anteile am BIP - Exporte",
        title1="",
        title2="",
        annual_series="AGE_QEX",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Anteile am BIP - Importe",
        title1="",
        title2="",
        annual_series="AGE_QIM",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Anteile am BIP - Lager",
        title1="",
        title2="",
        annual_series="AGE_QIL",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Nominales Lager",
        title1="",
        title2="",
        annual_series="AGE_IL_C_X",
        start_yr="2000",
        yaxis_title1="in Mrd. Euro",
        yaxis_format1=",.1f",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Lohnquote",
        title1="",
        title2="",
        annual_series="age_lohnq",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    # MFP_POT(
    #     title='bereinigte Lohnquote',
    #     title1="",
    #     title2="",
    #     annual_series="age_blohnq",
    #     start_yr="2000",
    #     yaxis_title1="in %",
    #     yaxis_format1=",.1%",
    #     yaxis_title2="",
    #     yaxis_format2="",
    # ),
    MFP_POT(
        title="Sparquote",
        title1="",
        title2="",
        annual_series="age_spq",
        start_yr="2000",
        yaxis_title1="in %",
        yaxis_format1=",.1%",
        yaxis_title2="",
        yaxis_format2="",
    ),
    MFP_POT(
        title="Erwerbstätige",
        title1="Personen (Level)",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_EW_X_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="Mio. Personen",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
        MFP_POT(
        title="Arbeitszeit",
        title1="Stunden (Level)",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_MFPAZEIT",
        start_yr=settings["window_mf"].start,
        yaxis_title1="Stunden",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
        MFP_POT(
        title="Arbeitsvolumen",
        title1="Volumen (Level)",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_AV_X_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="Mio. Stunden",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Produktivität pro Stunde",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_PRODH",
        start_yr=settings["window_mf"].start,
        yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Erwerbspersonen",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_EWP_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    # potenziell -- EU Methode
    MFP_POT(
        title="Erwerbstätige (tat. vs. pot., EU)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_EWPOTEU","AGE_EW_X_X"],
        start_yr=settings["window_mf"].start,
        yaxis_title1="in 1000 Personen",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Arbeitszeit (tat. vs. pot., EU)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_HOURSTEU_C_X", # das gibt es mit EU
                       "AGE_AZTATEU"],
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mio. Stunden",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Erwerbslosenquote (tat. vs. pot., EU)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_NAWRUEU",
                       "AGE_ALILOQ_X_C"],
    start_yr=settings["window_mf"].start,    
    yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Partizipationsquote (tat. vs. pot., EU)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_PARTSEU_C_X",
                       "AGE_PARTEU_C_X"],
    start_yr=settings["window_mf"].start,    
    yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Arbeitsvolumen (tat. vs. pot., EU)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_LPPOTEU",
                       "AGE_AV_X_X"],
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mio. Stunden",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Produktivität (tat. vs. pot., EU)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_PRODHEU",
                       "AGE_PRODH"],
    start_yr=settings["window_mf"].start,    
    yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
]

