
from collections import namedtuple
from ..settings import settings

MFP_POT = namedtuple("MFP_POT",
                 ["title","annual_series",
                  "title1", "title2",
                  "start_yr",
                  "yaxis_title1","yaxis_format1",
                  "yaxis_title2","yaxis_format2"])

mfp_pot = [
    # kind 1: alles mit Level und Change
    MFP_POT(
        title="Produktionspotenzial (EU)",
        title1="Verkettete Volumina",
        title2="Veränderung zum Vorjahr",
        annual_series="AGE_YPOTEU_C_X",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mrd. EUR",
        yaxis_format1=",.0f",
        yaxis_title2="in % zum Vorjahr",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Produktionslücke (EU)",
        title1="",
        title2="",
        annual_series="AGE_YGAPEU",
        start_yr=settings["window_mf"].start,
        yaxis_title1="in % des Potenzials",
        yaxis_format1=",.1f",
        yaxis_title2="",
        yaxis_format2="",
    ),
    
    MFP_POT(
        title="Erwerbstätige (tat. vs. pot.)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_EWPOTEU","AGE_EW_X_X"],
        start_yr=settings["window_mf"].start,
        yaxis_title1="in 1000 Personen",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Arbeitszeit (tat. vs. pot.)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_HOURSTEU_C_X", # das gibt es mit EU
                       "AGE_AZTATEU"],
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mio. Stunden",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Erwerbslosenquote (tat. vs. pot.)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_NAWRUEU",
                       "AGE_ALILOQ_X_C"],
    start_yr=settings["window_mf"].start,    
    yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Partizipationsquote (tat. vs. pot.)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_PARTSEU_C_X",
                       "AGE_PARTEU_C_X"],
    start_yr=settings["window_mf"].start,    
    yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Arbeitsvolumen (tat. vs. pot.)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_LPPOTEU",
                       "AGE_AV_X_X"],
        start_yr=settings["window_mf"].start,
        yaxis_title1="in Mio. Stunden",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
    MFP_POT(
        title="Produktivität (tat. vs. pot.)",
        title1="Level",
        title2="Veränderung zum Vorjahr",
        annual_series=["AGE_PRODHEU",
                       "AGE_PRODH"],
    start_yr=settings["window_mf"].start,    
    yaxis_title1="Index",
        yaxis_format1=",.0f",
        yaxis_title2="in %",
        yaxis_format2=",.1%",
    ),
]

